
import pandas as pd
import importlib.metadata # pandas-ta-openbb has a bug, requiring this to be imported first 
import pandas_ta as ta

from core import build_condition, evaluate_over
from data_retrieval import bracket_by_day, concat_days, downsample_days

def generate_signals(config, spot_df: pd.DataFrame, fut_df: pd.DataFrame):
    candles_1m = bracket_by_day(spot_df)

    timeframes = config["general"]["timeframes"]["intraday"]
    final_timeframe = f"{config["general"]["timeframes"]["smallest"]}min"

    # Column name aliases to replace those auto-generated by Pandas TA
    aliases = []

    for indicator in config["ta"]:
        a = indicator["alias"]
        if isinstance(a, list):
            aliases.extend(a)
        else:
            aliases.append(a)

    # Pandas TA Strategy for generating basic indicators
    SavedStrategy = ta.Strategy(
        name=config["name"],
        description=config["description"],
        ta=config["ta"],
    )

    # Generating data in different timeframes
    dfs = {}
    
    for timeframe in timeframes:
        tf = f"{timeframe}min"
        dfs[tf] = concat_days(downsample_days(candles_1m, tf))

        old_cols = dfs[tf].columns
        dfs[tf].ta.study(SavedStrategy)
        new_cols = dfs[tf].columns

        col_map = dict(zip(new_cols[len(old_cols):], aliases))
        dfs[tf].rename(columns=col_map, inplace=True)

        # Testing purposes only, limiting date
        # dfs[tf] = dfs[tf].loc["2026-07-01":]
    
    condition_cols = []

    # Apply conditions as new indicators across the main timeframe
    for c in config["conditions"]:
        condition_cols.append(c["id"])
        condition = build_condition(c)
        evaluate_over(condition, dfs, final_timeframe)
    
    df = dfs[final_timeframe]
    return df, condition_cols

    # Debug graphing

    addplots = []

    try_addplot("fast_ema", df, addplots, 0, None, "magenta")
    try_addplot("slow_ema", df, addplots, 0, None, "blue")
    try_addplot("vwap", df, addplots, 0, None, "gray")

    try_addplot("macd_line", df, addplots, 1, "MACD", "blue")
    try_addplot("macd_signal", df, addplots, 1, None, "orange")
    try_addplot("macd_histogram", df, addplots, 1, None, "gray", "bar")

    try_addplot("rsi", df, addplots, 2, "RSI", "gray")

    try_addplot("test_1", df, addplots, 3, "Conditions", "black")
    try_addplot("test_2", df, addplots, 3, None, "darkcyan")
    try_addplot("test_3", df, addplots, 3, None, "salmon")

    mpf.plot(
        df,
        type="candle",
        style="yahoo",
        volume=False,
        columns=["open", "high", "low", "close", "volume"],
        addplot=addplots if addplots else None,
        figsize=(24, 10),
        savefig=dict(fname=f"chart-x.png", dpi=400),
    )

def find_signal_onsets(df: pd.DataFrame, condition_cols: list[str]):
    result = {}
    for col in condition_cols:
        onset_timestamps = []
        onsets = (df[col] >= 0) & (df[col].shift(1) < 0)
        onset_timestamps = df.index[onsets]
        result[col] = onset_timestamps
    return result
